# Don't print a new line at the start of the prompt
format =  """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$character\
"""
add_newline = false
[directory]
truncate_to_repo = false
[line_break]
disabled = true
# Replace the "❯" symbol in the prompt with "➜"
[package]
disabled = true
